from __future__ import annotations

DEFAULT_STAGE_BATCH_MAX_ROWS = 100_000
DEFAULT_RECONCILE_BATCH_MAX_ROWS = 100_000
DEFAULT_RECONCILE_BATCH_MAX_BYTES: int | None = None

__all__ = [
    "DEFAULT_RECONCILE_BATCH_MAX_BYTES",
    "DEFAULT_RECONCILE_BATCH_MAX_ROWS",
    "DEFAULT_STAGE_BATCH_MAX_ROWS",
]
