from __future__ import annotations

from importlib import import_module
from typing import Any

__all__ = [
    "CanonicalKey",
    "CanonicalKeyScalar",
    "CanonicalKeyScalarKind",
    "CollectIdAllocator",
    "DestinationBatchCompletionState",
    "DestinationBatchIdentity",
    "DestinationBatchRecord",
    "DestinationBatchStatus",
    "DestinationScanRange",
    "DestinationProgress",
    "DestinationProgressScope",
    "DestinationProgressUpdate",
    "EventKeysetScanPosition",
    "OrderedWorkInput",
    "PendingWorkCursor",
    "PendingWorkPage",
    "OrderedWorkRow",
    "OrderedWorkStore",
    "RecoveryStore",
    "ReportStore",
    "RuntimeStore",
    "ScanPosition",
    "SqlCollectPlacement",
    "SqlRelationAccess",
    "SqlRelationSpace",
    "StateCurrentSnapshotScanPosition",
    "StateCurrentCursor",
    "StateCurrentPage",
    "StateCurrentSummary",
    "StateOrderedWorkScanPosition",
    "StateProductionResult",
    "StateProductionStore",
    "StateScanMode",
    "state_ordered_work_position_after",
    "StateSnapshotHandle",
    "StateSnapshotRequest",
    "StateSnapshotSource",
    "WorkFamily",
    "WorkKind",
    "canonical_key_from_jsonable",
    "canonical_key_scalar_from_jsonable",
    "canonical_key_scalar_to_jsonable",
    "canonical_key_to_jsonable",
    "compare_scan_positions",
    "destination_batch_id",
    "destination_scan_range_from_jsonable",
    "destination_scan_range_to_jsonable",
    "scan_position_from_jsonable",
    "scan_position_to_jsonable",
    "sql_collect_placement_from_jsonable",
    "sql_collect_placement_to_jsonable",
    "sql_relation_space_from_jsonable",
    "sql_relation_space_to_jsonable",
]


def __getattr__(name: str) -> Any:
    if name in {
        "CanonicalKey",
        "CanonicalKeyScalar",
        "CanonicalKeyScalarKind",
        "CollectIdAllocator",
        "DestinationBatchCompletionState",
        "DestinationBatchIdentity",
        "DestinationBatchRecord",
        "DestinationBatchStatus",
        "DestinationScanRange",
        "DestinationProgress",
        "DestinationProgressScope",
        "DestinationProgressUpdate",
        "EventKeysetScanPosition",
        "OrderedWorkInput",
        "PendingWorkCursor",
        "PendingWorkPage",
        "OrderedWorkRow",
        "OrderedWorkStore",
        "RecoveryStore",
        "ReportStore",
        "RuntimeStore",
        "ScanPosition",
        "SqlCollectPlacement",
        "SqlRelationAccess",
        "SqlRelationSpace",
        "StateCurrentSnapshotScanPosition",
        "StateCurrentCursor",
        "StateCurrentPage",
        "StateCurrentSummary",
        "StateOrderedWorkScanPosition",
        "StateProductionResult",
        "StateProductionStore",
        "StateScanMode",
        "state_ordered_work_position_after",
        "StateSnapshotHandle",
        "StateSnapshotRequest",
        "StateSnapshotSource",
        "WorkFamily",
        "WorkKind",
        "canonical_key_from_jsonable",
        "canonical_key_scalar_from_jsonable",
        "canonical_key_scalar_to_jsonable",
        "canonical_key_to_jsonable",
        "compare_scan_positions",
        "destination_batch_id",
        "destination_scan_range_from_jsonable",
        "destination_scan_range_to_jsonable",
        "scan_position_from_jsonable",
        "scan_position_to_jsonable",
        "sql_collect_placement_from_jsonable",
        "sql_collect_placement_to_jsonable",
        "sql_relation_space_from_jsonable",
        "sql_relation_space_to_jsonable",
    }:
        contracts = import_module("retl.stores.contracts")
        value = getattr(contracts, name)
        globals()[name] = value
        return value
    raise AttributeError(f"module `retl.stores` has no attribute `{name}`")
